### ISSUE TITLE
Feedback After Tournament

### ISSUE THREAD

**Issue by MatthewTompkins0804** [birkoss/mtg-tracker#2]
Hello! I went to a CEDH tournament recently and wrote down some notes I hope you’ll find helpful:

- Enabling Partner option doesn’t allow tracking of commander tax separately

- Partners don’t allow for differentiation (I.e., Red player with partners puts 2 identical red commander damage bubbles on everyone else’s screen). The ability to differentiate with names, symbols, numbers, or colors might be helpful. This is especially confusing when reading History as History doesn’t differentiate between commanders at all

- As above, history doesn’t differentiate between commanders at all. Following the minimal design language of the app, I might have commanders show up as some kind of colored bubble. For example:
> 🟠 Player #3 🟠
> 🔴 Commander Damage 🔴
> 0-10

- Additionally, maybe putting in parenthesis the actual life total change with commander damage. So if commander damage is 0-10 and the life total was at 40 you might read “0-10 (40-30)”

- Limited space for every optional tracker. If someone has Partner (or worse, every player has a partner as is common in CEDH) then the extra options for tracking Poison, Energy, Storm, and Experience all get pushed off screen. It would be helpful if these wrapped to a new column or overflowed to the bottom somehow. I know there’s only a total of seven spaces for trackers as stated in the settings, but it would still be nice if there was somehow a way for every option to fit

- Tracker for Rad Counters from fallout set?

**Comment by birkoss** [comment]
Hi!

Great feedback, thanks again!

I'll start with the easy changes : 

**- Tracking commander tax separately** and **differentiation between partner commander damages**

I grouped those together. If I only add the partner commander tax tracking, the same issue will occurs with the differentiation.

I'll add the tracking for partner taxes (when a partner is enabled). I don't know how I missed this. I run a Partners in my cEDH deck but I really care about one of them.

I'll also find a way to differentiate both boxes. I had feedback regarding colors (by a color blind person before). I'll try to find a way to make it work for everyone.

**- Tracker for Rad Counters**

I'll add those in the next build.

For the remaining suggestions : 

Regarding the **history**, I added this a while back but I never really used it personally. I understand now how it can be used. I'll see if I can fine tuned this to make it much clearer and useful.

**Limited space for every optional tracker**

This is something that I struggled with since the beginning. For example, when more than 4 players are selected, I choose to hide those trackers.

Since the settings button is always visible at the bottom left, no matter what, maybe I should add another "action" button at the bottom right with an arrow to be able to "scroll". This would allow to show 6 extra trackers (13 instead of 7).


I can't make any promises on when everything will be done, but there will probably be an update by Monday to address some of these points.

**Comment by birkoss** [comment]
I have submitted a new release on the app stores for those issues, should be available within 24 hours.

However...

The difference between Commander and Partner Commander Damage bubble are not final. I simply added a "C" for the Commander Damage bubble, and a "P" for the Partner Damage bubble. The label once clicked will show "Commander Damage" or "Partner Damage".

I'll ask advices to my Artistic Director at work back on Tuesday. Maybe something like a notification icon (the red circle with a M or P in it).

Same thing with the Partner Commander Tax. For now, it's the same icon (with the "Commander Tax" or "Partner Tax" label when selected).

The same indication will be added from the Commander Bubble on the Tax Bubble for consistency when a solution will be chosen.

Let me know how the remaining things works for you.
